
package cn.ldm.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.ldm.cn/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<cn.ldm.service.Customer>
     */
    @WebMethod(operationName = "CustomerService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CustomerService", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.CustomerService_Type")
    @ResponseWrapper(localName = "CustomerServiceResponse", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.CustomerServiceResponse")
    public List<Customer> customerService();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.ldm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associationSelect", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.AssociationSelect")
    @ResponseWrapper(localName = "associationSelectResponse", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.AssociationSelectResponse")
    public List<Customer> associationSelect(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.ldm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomer", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.FindCustomer")
    @ResponseWrapper(localName = "findCustomerResponse", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.FindCustomerResponse")
    public Customer findCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.ldm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.ldm.cn/", className = "cn.ldm.service.FindAllResponse")
    public List<Customer> findAll();

}
